name: pipeline-demo
description: https://github.com/Green-Software-Foundation/if-unofficial-plugins/issues/81
tags: null
initialize:
  plugins:
    azure-importer:
      path: '@grnsft/if-unofficial-plugins'
      method: AzureImporter
    try-defaults-1:
      path: 'builtin'
      method: Coefficient
      global-config:
        input-parameter: grid/carbon-intensity
        coefficient: 0.1
        output-parameter: grid/carbon-intensity
    try-defaults-2:
      path: 'builtin'
      method: Coefficient
      global-config:
        input-parameter: network/energy
        coefficient: 1000
        output-parameter: network/energy
    "operational-carbon":
      method: Multiply
      path: builtin
      global-config:
        input-parameters: ["energy", "grid/carbon-intensity"]
        output-parameter: "carbon-operational"
    group-by:
      path: builtin
      method: GroupBy
  outputs:
    - yaml
if-version: v0.3.2
tree:
  children:
    web-front:
      pipeline:
        - azure-importer
        - try-defaults-1
        - try-defaults-2
      config:
        group-by:
          group:
            - instance-type
        azure-importer:
          azure-observation-window: 60 min
          azure-observation-aggregation: average
          azure-subscription-id: 30b6e171-af2c-4fe6-b00d-d4c70f6291fe
          azure-resource-group: gcf-app_group
          azure-vm-name: gcf-app
      defaults:
        grid/carbon-intensity: 800
        network/energy: 0.001
      inputs:
        - timestamp: '2024-04-04T08:00:00.001Z'
          duration: 3600
          energy: 100
   