name: sci-embodied
description: successful path
tags:
initialize:
  plugins:
    "csv-lookup":
      path: builtin
      method: CSVLookup
      config:
        filepath: >-
          https://raw.githubusercontent.com/Green-Software-Foundation/if-data/main/cloud-metdata-azure-instances.csv
        query:
          instance-class: cloud/instance-type
        output: ["cpu-cores-utilized", "vcpus-allocated"]
    "sci-embodied": # a model that calculates m from te, tir, el, rr and rtor
      method: SciEmbodied
      path: "builtin"
tree:
  children:
    child:
      pipeline:
        compute:
          - csv-lookup
          - sci-embodied # duration & config -> embodied
      defaults:
        device/emissions-embodied: 1533.120 # gCO2eq
        time-reserved: 3600 # 1hr in seconds
        device/expected-lifespan: 94608000 # 3 years in seconds
        resources-reserved: 1
        resources-total: 8
      inputs:
        - timestamp: 2023-07-06T00:00
          duration: 3600
          cloud/vendor: intel
          cloud/instance-type: Standard_A1_v2
          cpu/utilization: 10
