name: input-error-missing-duration
description: a negative test case that fails due to the required `duration` field being omitted from input data
tags:
initialize:
  plugins:
    "interpolate":
      method: Interpolation
      path: builtin
      config:
        method: linear
        x: [0, 10, 50, 100]
        y: [0.12, 0.32, 0.75, 1.02]
        input-parameter: 'cpu/utilization'
        output-parameter: 'cpu-factor'
tree:
  children:
    child-0:
      defaults:
        cpu/thermal-design-power: 100
      pipeline:
        compute:
          - interpolate
      inputs:
        - timestamp: 2023-07-06T00:00
          cpu/utilization: 20
